#端口号配置
server:
  port: 80
#数据库配置
spring:
  datasource:
    url: jdbc:mysql://120.55.44.72:3306/cms?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: utf-8
  mvc:
    static-path-pattern: /static/**
#MyBatis-Plus配置


# 实体扫描，多个package用逗号或者分号分隔
mybatis-plus:
  type-aliases-package: com.cn.cms.entity
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    id-type: 2  # 主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    field-strategy: 2 # 字段策略 0:"忽略判断",1:"非 NULL 判断",2:"非空判断"
    db-column-underline: true # 驼峰下划线转换
  configuration:
    map-underscore-to-camel-case: true # 开启查询结果下划线转驼峰
    cache-enabled: false

#加载日志配置文件
logging:
  config: classpath:log4j2.xml